apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: workspace-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vagrant/workspace-storage"
